version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=skynet
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - hajime
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=skynet
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - hajime

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - 5601:5601
    networks:
      - hajime

  cowrie:
    build: .
    ports:
      - 2222:2222
      - 2223:2223
    volumes:
      - cowrie_log:/home/cowrie/cowrie/log
    depends_on:
      - mongo
    networks:
      - mirai

  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.1
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - cowrie_log:/var/log/cowrie
    networks:
      - hajime

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - mirai

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  mongodata:
    driver: local
  cowrie_log:
    driver: local

networks:
  hajime:
  mirai:
